"""
backend/services/composition_service.py
Orchestration layer: combines chord, melody, and drum services into a single
unified composition and serialises it to Standard MIDI File bytes.

This module contains NO music-theory logic and NO MIDI construction logic.
Every domain decision is delegated to the appropriate subsystem:
  · Harmony / voicing  → chord_service   (chord_data is pre-generated by caller)
  · Melodic content    → melody_service.generate_melody()
  · Rhythmic content   → drum_service.generate_drums()
  · MIDI serialisation → midi/builder.py, midi/melody_writer.py, midi/drum_writer.py

Beat-grid alignment guarantee
──────────────────────────────
All three subsystems share a common beat coordinate system:
  · Beats are floats (quarter notes), 0-indexed from the composition start.
  · The shared constant PPQ = 480 (rhythm.PPQ == builder.MidiBuilder.PPQ).
  · Chord, melody, and drum events are all generated for the same bars value,
    so max(event.beat) < bars * beats_per_bar for every subsystem.
  · MidiBuilder converts beats → ticks via round(beat * PPQ) at serialisation time,
    so all three parts resolve to the same tick grid.
No resampling or conversion is needed here — alignment is structural.

Public API
──────────
  compose(chord_data, melody_octave, melody_density, chord_instrument,
          melody_instrument, drum_variation_bars, seed,
          include_melody, include_drums)  → dict

Input
  chord_data  Output of chord_service.generate_chord_progression().
              Provides key, mode, scale, genre, bpm, bars, time_signature,
              chords, chord_scale for melody pitch selection.

Output
  {
    key, mode, scale, genre, bpm, bars, time_signature,
    ppq,           int      480 — shared tick resolution
    total_beats,   float    bars * beats_per_bar
    parts,         list     ['chords', 'melody', 'drums'] (subset when excluded)
    tracks,        dict     part name → MidiBuilder track index
    chord_data,    dict     chord_service output (echoed for caller convenience)
    melody_data,   dict     melody_service output, or None if excluded
    drum_data,     dict     drum_service output, or None if excluded
    midi_bytes,    bytes    raw SMF bytes — route layer base64-encodes for JSON
    summary,       dict     {'track_count': N, 'note_count': N}
  }

Route integration (POST /api/generate/composition)
───────────────────────────────────────────────────
  1. Route parses request body, validates key + mode.
  2. Route calls generate_chord_progression(...) → chord_data.
  3. Route calls compose(chord_data, ...) → result.
  4. Route replaces result['midi_bytes'] with base64.b64encode(...).decode('ascii')
     under the key 'midi', then returns jsonify(response).
  See routes/generation.py for the full handler.
"""

from __future__ import annotations

from backend.services.drum_service import generate_drums
from backend.services.melody_service import generate_melody
from midi.builder import MidiBuilder, build_from_chord_progression
from midi.drum_writer import write_drums
from midi.melody_writer import write_melody
from music_theory.rhythm import PPQ


def compose(
    chord_data: dict,
    melody_octave: int = 5,
    melody_density: float = 0.75,
    chord_instrument: str | int = 'piano',
    melody_instrument: str | int = 'piano',
    drum_variation_bars: int = 4,
    seed: int | None = None,
    include_melody: bool = True,
    include_drums: bool = True,
) -> dict:
    """
    Orchestrate chord + melody + drum generation into a unified MIDI composition.

    Parameters
    ----------
    chord_data : dict
        Output of chord_service.generate_chord_progression().
        Drives melody pitch selection, drum genre/bpm/bars, and MIDI metadata.
    melody_octave : int
        Centre octave for the melody register.  Melody spans [C(octave-1), C(octave+1)].
        Default 5 puts the melody above a chord register of 4.
    melody_density : float
        Fraction of rhythm slots that become melody notes (0.0-1.0).
        Strong-beat slots always play regardless of density.
    chord_instrument : str | int
        GM instrument for the chords track.  String key from GM_PROGRAMS or 0-127 int.
    melody_instrument : str | int
        GM instrument for the melody track.
    drum_variation_bars : int
        Apply a genre drum fill at the end of every N bars (0 = disabled).
    seed : int | None
        Shared RNG seed passed to melody_service and drum_service for
        reproducible humanization.  None produces non-deterministic output.
    include_melody : bool
        When False, the melody track is omitted from the composition.
    include_drums : bool
        When False, the drum track is omitted from the composition.

    Returns
    -------
    dict
        Unified composition dict.  See module docstring for full schema.
        midi_bytes is a raw bytes object; callers that need JSON must base64-encode it.
    """
    genre = chord_data['genre']
    bpm   = chord_data['bpm']
    bars  = chord_data['bars']
    ts    = chord_data.get('time_signature', [4, 4])
    beats_per_bar = ts[0]
    total_beats   = float(bars * beats_per_bar)

    # ── Generate constituent parts ─────────────────────────────────────────────
    melody_data: dict | None = None
    drum_data:   dict | None = None

    if include_melody:
        melody_data = generate_melody(
            chord_data,
            octave  = melody_octave,
            density = melody_density,
            seed    = seed,
        )

    if include_drums:
        drum_data = generate_drums(
            genre          = genre,
            bars           = bars,
            bpm            = bpm,
            seed           = seed,
            variation_bars = drum_variation_bars,
        )

    # ── Assemble into a single MidiBuilder ────────────────────────────────────
    # build_from_chord_progression creates the builder, sets tempo + time signature,
    # and writes track 0 (Chords).  Additional tracks are appended in order.
    builder: MidiBuilder = build_from_chord_progression(
        chord_data, instrument=chord_instrument
    )

    tracks: dict[str, int] = {'chords': 0}

    if melody_data is not None:
        tracks['melody'] = write_melody(
            builder, melody_data, instrument=melody_instrument
        )

    if drum_data is not None:
        tracks['drums'] = write_drums(builder, drum_data)

    midi_bytes = builder.to_bytes()

    # ── Build parts list in consistent order ──────────────────────────────────
    parts: list[str] = ['chords']
    if melody_data is not None:
        parts.append('melody')
    if drum_data is not None:
        parts.append('drums')

    return {
        'key':            chord_data['key'],
        'mode':           chord_data['mode'],
        'scale':          chord_data['scale'],
        'genre':          genre,
        'bpm':            bpm,
        'bars':           bars,
        'time_signature': ts,
        'ppq':            PPQ,
        'total_beats':    total_beats,
        'parts':          parts,
        'tracks':         tracks,
        'chord_data':     chord_data,
        'melody_data':    melody_data,
        'drum_data':      drum_data,
        'midi_bytes':     midi_bytes,
        'summary':        builder.summary(),
    }
